// Bundle-v1 wire presence/type contract, captured from B-1 serialization.
// Every listed field is required even if the old client model has a default.
// This is a small domain shape description, not an executable policy/schema.
// DB CHECK domains apply to raw Snapshot and matching presentation fields.
// Do not invent enums for unconstrained historical entry_kind/panel_type/etc.
const bundleFiniteDomains = <String, Set<String>>{
  'book_section': {'current', 'archive'},
  'event_type': {'immediate', 'discount'},
  'registration_target': {'ledger', 'claim', 'family_card'},
  // Current backend policy classes and v1 projection rounding vocabulary.
  'policy_type': {'flat_statement', 'no_automatic_discount'},
  'policy_rounding': {'floor', 'none'},
};

const bundleWireShapes = <String, Map<String, String>>{
  'Bundle': {
    'bundle_version': 'c:1',
    'principal': '@BundlePrincipal',
    'authority': '@BundleAuthority',
    'snapshot': '@Snapshot',
    'state': '@AuthoritativeProjections',
  },
  'AuthoritativeProjections': {
    'month_close_status': '@MonthCloseStatus',
    'entries': '[@LedgerEntry]',
    'panels': '[@MonthlyPanel]',
    'summary': '@Summary',
    'card_payment_status': '@PaymentStatus',
    'judgment': '@Judgment',
    'confirmed_planned_entries': '[@LedgerEntry]',
    'cash_flows': '[@CashFlow]',
    'settings': '{s}',
    'owner_discount_month': '@DiscountMonth',
    'family_discount_month': '@DiscountMonth',
    'transit_discount_profile': '@TransitProfile',
  },
  'BundleAuthority': {
    'state_revision': 'i',
    'state_fingerprint': 'h',
    'evaluation_date': 'd',
    'discount_policy_defaults': '@DiscountPolicyDefaults',
  },
  'BundlePrincipal': {
    'user_id': 'i',
  },
  'CashFlow': {
    'id': 'i',
    'occurred_on': 'd',
    'title': 's',
    'amount_value': 'n',
    'sort_order': 'i',
    'is_primary_income': 'i',
  },
  'DiscountMonth': {
    'month': 'm',
    'scope': 's',
    'policy': 's',
    'projection_policy': '@ProjectionPolicy',
    'discounts': '{n}',
    'discount_total': 'n',
  },
  'DiscountPolicyDefaults': {
    'owner': 'e:enabled,disabled',
    'family': 'e:enabled,disabled',
  },
  'Judgment': {
    'category_labels': '{s}',
    'stat_tones': '[@StatTone]',
    'claim_categories': '{s}',
    'budget': '@JudgmentMessage',
    'credit': '@JudgmentMessage',
    'payment': '@JudgmentMessage',
  },
  'JudgmentMessage': {
    'level': 's',
    'message': 's',
  },
  'LedgerEntry': {
    'book_section': 'v:book_section',
    'entry_kind': 's',
    'entry_date': '?d',
    'date_label': '?s',
    'group_label': '?s',
    'title': 's',
    'usage_place': '?s',
    'usage_item': '?s',
    'amount_value': '?n',
    'amount_expr': '?s',
    'aux_amount_value': '?n',
    'aux_amount_expr': '?s',
    'extra_value': '?s',
    'sort_order': 'i',
    'due_day': '?i',
    'confirmed_at': '?s',
    'confirmed_month': '?m',
    'spending_category': '?s',
    'payment_key': '?s',
    'discount_override': 'i',
    'id': 'i',
    'discount_policy': 's',
    'automatic_discount_eligible': 'b',
    'automatic_discount_amount': 'n',
    'effective_discount_amount': 'n',
    'effective_amount_value': '?n',
    'is_transport': 'b',
    'is_toll': 'b',
    'confirmed_amount_value': '?n',
    'confirmed_effective_discount_amount': '?n',
    'confirmed_effective_amount_value': '?n',
  },
  'MonthCloseStatus': {
    'calendar_date': 'd',
    'calendar_month': 'm',
    'oldest_open_month': '?m',
    'last_closed_month': '?m',
    'needs_close': 'b',
    'is_early_close': 'b',
    'early_close_available': 'b',
    'early_close_start_day': 'i',
    'card_recurring_confirmation_available': 'b',
    'can_close': 'b',
    'unconfirmed_recurring_items': '[@RecurringCloseItem|@PlannedCloseItem]',
  },
  'MonthlyPanel': {
    'id': 'i',
    'month': 'm',
    'panel_type': 's',
    'title': 's',
    'spent_on': '?d',
    'amount_value': '?n',
    'discount_amount': 'n',
    'discount_override': 'i',
    'amount_expr': '?s',
    'sort_order': 'i',
    'due_day': '?i',
    'confirmed_at': '?s',
    'confirmed_cash_flow_id': '?i',
    'confirmed_month': '?m',
    'can_confirm_fixed': 'b',
    'fixed_execution_month': '?m',
    'discount_policy': 's',
    'automatic_discount_eligible': 'b',
    'automatic_discount_amount': 'n',
    'effective_discount_amount': 'n',
    'effective_amount_value': '?n',
    'confirmed_amount_value': '?n',
  },
  'PaymentEvent': {
    'id': 'i',
    'batch_id': '?i',
    'event_date': 'd',
    'event_type': 'v:event_type',
    'total_amount': 'n',
    'note': '?s',
    'cash_flow_id': '?i',
    'idempotency_key': '?s',
    'request_fingerprint': '?s',
    'created_at': 's',
  },
  'PaymentPart': {
    'entry_payment_key': 's',
    'entry_id': 'i',
    'remaining_amount': 'n',
  },
  'PaymentRow': {
    'id': 'i',
    'book_section': 'v:book_section',
    'entry_kind': 's',
    'entry_date': '?d',
    'date_label': '?s',
    'group_label': '?s',
    'title': 's',
    'usage_place': '?s',
    'usage_item': '?s',
    'amount_value': '?n',
    'amount_expr': '?s',
    'aux_amount_value': '?n',
    'aux_amount_expr': '?s',
    'extra_value': '?s',
    'sort_order': 'i',
    'due_day': '?i',
    'confirmed_at': '?s',
    'confirmed_month': '?m',
    'source_planned_entry_id': '?i',
    'spending_category': '?s',
    'payment_key': '?s',
    'discount_override': 'i',
    'created_at': 's',
    'updated_at': 's',
    'original_amount': 'n',
    'immediate_paid_amount': 'n',
    'discount_amount': 'n',
    'discount_policy': 's',
    'automatic_discount_eligible': 'b',
    'automatic_discount_amount': 'n',
    'effective_discount_amount': 'n',
    'effective_amount_value': 'n',
    'remaining_amount': 'n',
    'is_transport': 'b',
    'is_toll': 'b',
    'is_deferred': 'b',
    'is_carried_over': 'b',
    'payment_keys': '[s]',
    'entry_ids': '[i]',
    'payment_parts': '[@PaymentPart]',
    'is_group': 'b',
  },
  'PaymentStatus': {
    'calendar_date': 'd',
    'payment_month': 'm',
    'usage_month': 'm',
    'due_date': 'd',
    'immediate_allowed': 'b',
    'needs_liquidity_reset': 'b',
    'liquidity_reset_acknowledged': 'b',
    'original_total': 'n',
    'immediate_paid_total': 'n',
    'discount_total': 'n',
    'recorded_remaining_total': 'n',
    'effective_remaining_total': 'n',
    'primary_income_total': 'n',
    'discount_policy': 's',
    'rows': '[@PaymentRow]',
    'events': '[@PaymentEvent]',
  },
  'PlannedCloseItem': {
    'kind': 'e:planned',
    'id': 'i',
    'title': 's',
    'detail': 's',
    'amount_value': 'n',
    'due_day': '?i',
  },
  'ProjectionPolicy': {
    'schema_version': 'i',
    'policy_id': 's',
    'type': 'v:policy_type',
    'parameters': '{j}',
    'rounding': 'v:policy_rounding',
  },
  'RecurringCloseItem': {
    'kind': 'e:fixed',
    'id': 'i',
    'title': 's',
    'amount_value': '?n',
  },
  'StatTone': {
    'key': '?s',
    'title': 's',
    'caption': 's',
  },
  'Summary': {
    'scheduled_income': 'n',
    'cash_flow_balance': 'n',
    'remaining_liquidity': 'n',
    'current_month_spendable': 'n',
    'current_spending_total': 'n',
    'current_discount_total': 'n',
    'card_total': 'n',
    'planned_recurring_total': 'n',
    'fixed_cash_total': 'n',
    'fixed_cash_processed_total': 'n',
    'transfer_or_deposit_total': 'n',
    'frozen_asset_total': 'n',
    'claim_original_total': 'n',
    'claim_net_total': 'n',
    'family_card_original_total': 'n',
    'family_card_net_total': 'n',
    'visible_cash_flow_total': 'n',
  },
  'TransitProfile': {
    'card': 's',
    'month': 'm',
    'profile': 's',
  },
  'Snapshot_ledger_entries': {
    'id': 'i',
    'book_section': 'v:book_section',
    'entry_kind': 's',
    'entry_date': '?d',
    'date_label': '?s',
    'group_label': '?s',
    'title': 's',
    'usage_place': '?s',
    'usage_item': '?s',
    'amount_value': '?n',
    'amount_expr': '?s',
    'aux_amount_value': '?n',
    'aux_amount_expr': '?s',
    'extra_value': '?s',
    'sort_order': 'i',
    'due_day': '?i',
    'confirmed_at': '?s',
    'confirmed_month': '?m',
    'source_planned_entry_id': '?i',
    'spending_category': '?s',
    'payment_key': '?s',
    'discount_override': 'i',
    'created_at': 's',
    'updated_at': 's',
  },
  'Snapshot_monthly_panels': {
    'id': 'i',
    'month': 'm',
    'panel_type': 's',
    'title': 's',
    'spent_on': '?d',
    'amount_value': '?n',
    'discount_amount': 'n',
    'discount_override': 'i',
    'amount_expr': '?s',
    'sort_order': 'i',
    'due_day': '?i',
    'confirmed_at': '?s',
    'confirmed_month': '?m',
    'confirmed_cash_flow_id': '?i',
    'created_at': 's',
    'updated_at': 's',
  },
  'Snapshot_cash_flows': {
    'id': 'i',
    'occurred_on': 'd',
    'title': 's',
    'amount_value': 'n',
    'sort_order': 'i',
    'is_primary_income': 'i',
    'created_at': 's',
    'updated_at': 's',
  },
  'Snapshot_card_payment_batches': {
    'id': 'i',
    'usage_month': 'm',
    'source': 's',
    'status': 's',
    'created_at': 's',
  },
  'Snapshot_card_payment_batch_items': {
    'id': 'i',
    'batch_id': 'i',
    'entry_id': 'i',
    'entry_payment_key': 's',
    'created_at': 's',
  },
  'Snapshot_card_payment_events': {
    'id': 'i',
    'batch_id': '?i',
    'event_date': 'd',
    'event_type': 'v:event_type',
    'total_amount': 'n',
    'note': 's',
    'cash_flow_id': '?i',
    'idempotency_key': '?s',
    'request_fingerprint': '?s',
    'created_at': 's',
  },
  'Snapshot_card_payment_allocations': {
    'id': 'i',
    'payment_event_id': 'i',
    'entry_payment_key': 's',
    'amount_value': 'n',
    'created_at': 's',
  },
  'Snapshot_card_payment_deferrals': {
    'entry_payment_key': 's',
    'from_payment_month': 'm',
    'target_payment_month': 'm',
    'original_book_section': '?s',
    'original_entry_date': '?d',
    'original_date_label': '?s',
    'original_group_label': '?s',
    'original_title': '?s',
    'original_sort_order': '?i',
    'created_at': 's',
  },
  'Snapshot_notification_candidate_registrations': {
    'registration_key': 's',
    'target': 'v:registration_target',
    'target_id': 'i',
    'request_fingerprint': 's',
    'created_at': 's',
  },
  'Snapshot_app_settings': {
    'key': 's',
    'value': 's',
    'updated_at': 's',
  },
  'Snapshot_app_labels': {
    'key': 's',
    'value': 's',
    'updated_at': 's',
  },
  'Snapshot': {
    'schema_version': 'c:7',
    'recurring_ownership_version': 'c:1',
    'exported_at': 's',
    'range': '@SnapshotRange',
    'card_charge_policy': '@SnapshotPolicy',
    'data': '@SnapshotData',
    'manifest': '@SnapshotManifest',
    'snapshot_id': 'h',
  },
  'SnapshotRange': {
    'scope': 'e:all',
  },
  'SnapshotData': {
    'ledger_entries': '[@Snapshot_ledger_entries]',
    'monthly_panels': '[@Snapshot_monthly_panels]',
    'cash_flows': '[@Snapshot_cash_flows]',
    'card_payment_batches': '[@Snapshot_card_payment_batches]',
    'card_payment_batch_items': '[@Snapshot_card_payment_batch_items]',
    'card_payment_events': '[@Snapshot_card_payment_events]',
    'card_payment_allocations': '[@Snapshot_card_payment_allocations]',
    'card_payment_deferrals': '[@Snapshot_card_payment_deferrals]',
    'notification_candidate_registrations':
        '[@Snapshot_notification_candidate_registrations]',
    'app_settings': '[@Snapshot_app_settings]',
    'app_labels': '[@Snapshot_app_labels]',
  },
  'SnapshotManifest': {
    'algorithm': 'e:sha256',
    'tables': '@SnapshotTables',
    'data_sha256': 'h',
    'card_charge_policy_sha256': 'h',
    'content_sha256': 'h',
  },
  'SnapshotTables': {
    'ledger_entries': '@SnapshotTable',
    'monthly_panels': '@SnapshotTable',
    'cash_flows': '@SnapshotTable',
    'card_payment_batches': '@SnapshotTable',
    'card_payment_batch_items': '@SnapshotTable',
    'card_payment_events': '@SnapshotTable',
    'card_payment_allocations': '@SnapshotTable',
    'card_payment_deferrals': '@SnapshotTable',
    'notification_candidate_registrations': '@SnapshotTable',
    'app_settings': '@SnapshotTable',
    'app_labels': '@SnapshotTable',
  },
  'SnapshotTable': {
    'columns': '[s]',
    'row_count': 'i',
    'sha256': 'h',
  },
  'SnapshotPolicy': {
    'schema_version': 'c:2',
    'classifier': '@PolicyClassifier',
    'profile_selectors': '@PolicySelectors',
    'cards': '@SnapshotCards',
    'covered_through': 'm',
  },
  'PolicyClassifier': {
    'schema_version': 'c:1',
    'matching': 's',
    'precedence': '[s]',
    'toll_words': '[s]',
    'transit_words': '[s]',
  },
  'PolicySelectors': {'transit': '@TransitSelector'},
  'TransitSelector': {
    'schema_version': 'c:1',
    'card': 's',
    'default': 's',
    'modes': '[s]',
    'none_mode': '@TransitNoneMode',
    'owner_mode': '@TransitOwnerMode',
    'selection': 's',
    'setting_prefix': 's',
  },
  'TransitNoneMode': {'policy': '@PolicyDefinition'},
  'TransitOwnerMode': {'policy_source': 's', 'month_policy_source': 's'},
  'PolicyDefinition': {
    'policy_id': 's',
    'type': 'v:policy_type',
    'parameters': '{j}'
  },
  'SnapshotCards': {
    'owner': '[@PolicyBinding]',
    'family': '[@PolicyBinding]',
    'toll': '[@PolicyBinding]',
    'transit': '[@PolicyBinding]',
  },
  'PolicyBinding': {
    'effective_from': 'm',
    'policy_id': 's',
    'type': 'v:policy_type',
    'parameters': '{j}',
  },
};
