"""Print the mobile admission-only policy artifact from the backend registry.

This is trusted build metadata, not a client discount calculator. --check is a
read-only parity gate: a server registry change requires deliberate regeneration
and review, never acceptance of a new definition supplied by a bundle itself.
"""

import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "backend"))

from app.services.card_charge.registry import card_charge_policy_manifest  # noqa: E402

TARGET = ROOT / "mobile/lib/src/generated/bundle_policy_manifest.dart"


def generated_source() -> str:
    manifest = json.dumps(card_charge_policy_manifest(), ensure_ascii=False,
                          sort_keys=True, indent=2)
    return (
        "// Generated by scripts/generate_bundle_policy.py; do not edit by hand.\n"
        "// Admission identity only: never execute these definitions as financial rules.\n"
        "const canonicalBundlePolicyJson = r'''\n" + manifest + "\n''';\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    source = generated_source()
    if args.check:
        if not TARGET.is_file() or TARGET.read_text() != source:
            print("mobile canonical policy artifact is stale", file=sys.stderr)
            return 1
    else:
        print(source, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
